# Configurações de Porta do Servidor Tomcat
server.port=8080

# BANCO DE DADOS PADRÃO: H2 (Banco em memória relacional para desenvolvimento ágil)
spring.datasource.url=jdbc:h2:mem:financapro_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console Web do Banco de Dados H2 habilitado em http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# BANCO ALTERNATIVO (Descomente para conectar ao PostgreSQL de produção)
# spring.datasource.url=jdbc:postgresql://localhost:5432/financapro_db
# spring.datasource.username=postgres
# spring.datasource.password=secret_db_password
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Inicializador Hibernate DDL (Gera e atualiza tabelas automaticamente no banco)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ajuste de fusos e internacionalização
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.date-format=yyyy-MM-dd
